dist: xenial
language: python
python:
	- "3.7"
	- "3.6"
install:
	- pip install -e .
deploy:
  provider: pypi
  user: subhrajitpy
  password:
    secure: gwm6OkDmm26wTFNnRJosonC5f9KO/OVqUf6Zfy3xGWIupYFSD/xg+JWY6JdJwPO0/zFpe4n6cNh09BKINsC3iTr+JRXCpnO3qWB+3tfGF6hbrT17EEdaJ5lTDrysjADNtvrMzElkxPNyzj6uDTdwuJE7ZOn6YuEJUJDmZjOKQQcoM5oxxIE7aWTuzAc3bEutuRJ2BAMr64IGHpbkbKtOZBIOzcMlMvwe+ZKkmFw7QKNiUQeWegU3pG7Dut1JbykgMPJ3E3najusnL/xl/RnVS+0jAnfonnXJXLiFamn5igT33DsVwbRCd0tQCrdpvW/K9H2HobFWe9RG4HBlH/SJjuHY2uH+CZ+8yzrcCFcFRfdHZ+A/Yl922z1JMY7k+7FlWv+hlds1+RGQAILhVJMk+DyXOY9cn9sxctnzWm2noRQ1lHWNAWKxfTNxSM6idFki3xwZJFxI+7r3I27jiGkRf3CYF8nz6pKuQnPfn2iW+jtOPLnWDw7nCt5sEV+CX5ucK3LqHUEm+i5ua4HhA9reA0l67Z8XCyb7gyCR17Tf5w5noJwqf2NmvGqipM7ez0kUvbHURK+tXus7KQJr7mI//1zoOTYwL4ggpPlVRdmpY8aZQxku+bzocjYWEH1fAmf82zi4+XWbTeJZ1/Y0ziEaSe345cbqjvzl80YaMCo/BAU=
